_format_version: "3.0"
_transform: true

services:
  - host: mockbin.org
    name: example_service
    port: 80
    protocol: http
    routes:
    - name: example_route
      paths:
      - /mock
      strip_path: true
