version: "3.9"
networks:
  kong-net:
    external: false
services:
  kong-database:
    image: postgres
    container_name: kong-database
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_DB: "kong"
      POSTGRES_USER: "kong"
      POSTGRES_PASSWORD: "kongpass"
    ports:
      - "5432:5432"
  kong-bootstrap:
    image: kong/kong-gateway
    hostname: kong-bootstrap
    container_name: kong-bootstrap
    restart: on-failure
    depends_on:
      - kong-database
    networks:
      - kong-net
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_PASSWORD: "kongpass"
    command: "kong migrations bootstrap"
  kong-api-postgres-mode:
    image: kong/kong-gateway
    hostname: kong-api-postgres-mode
    container_name: kong-api-postgres-mode
    restart: always
    depends_on:
      - kong-bootstrap
    networks:
      - kong-net
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kongpass"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
      KONG_LICENSE_DATA: "/etc/kong/license.json"
      KONG_PORTAL_GUI_HOST: "localhost:8003"
      KONG_PORTAL: "on"
    command: "kong start"
    ports:
      # Port Routing for Application API's
      - 8000:8000
      # Port Routing for Admin API's
      - 8001:8001
      # Port Routing for Admin Dashboard
      - 8002:8002
      # Port Routing for Dev Portal
      - 8003:8003
    volumes:
      - ./config:/etc/kong
